removed name

diff --git a/.github/workflows/update-readme.yaml b/.github/workflows/update-readme.yaml
--- a/.github/workflows/update-readme.yaml
+++ b/.github/workflows/update-readme.yaml
@@ -41,30 +41,28 @@ jobs:
 
       # Check if there are any open PRs
       if [ "$(echo $PR_RESPONSE | jq length)" -gt 0 ]; then
-      PR_NUMBER=$(echo $PR_RESPONSE | jq '.[0].number')
-      echo "::set-output name=pr_number::$PR_NUMBER"
+        PR_NUMBER=$(echo $PR_RESPONSE | jq '.[0].number')
+        echo "::set-output name=pr_number::$PR_NUMBER"
 
-      python .github/workflows/genimage.py "$PR_NUMBER Open" || { echo "Python script failed"; exit 1; }
+        python .github/workflows/genimage.py "$PR_NUMBER Open" || { echo "Python script failed"; exit 1; }
 
-      git diff --exit-code pics/*.png
-        if [ $? -eq 0 ]; then
-        echo "No changes in the image files, skipping commit."
-        else
-        # Stage the changed image files
-        git add pics/*.png
-        
-        # Commit the changes
-        git commit -m "Update README status with latest PR number"
-        
-        # Push the changes to the remote repository
-        git push https://x-access-token:${{ secrets.FINE_GRAINED_TOKEN }}@github.com/${{ github.repository }}.git
-        fi
+        git diff --exit-code pics/*.png
+          if [ $? -eq 0 ]; then
+            echo "No changes in the image files, skipping commit."
+          else
+            # Stage the changed image files
+            git add pics/*.png
+
+            # Commit the changes
+            git commit -m "Update README status with latest PR number"
+          
+            # Push the changes to the remote repository
+            git push https://x-access-token:${{ secrets.FINE_GRAINED_TOKEN }}@github.com/${{ github.repository }}.git
+          fi
       else
-      echo "No open pull requests found."
-      echo "::set-output name=pr_number::none"
+        echo "No open pull requests found."
+        echo "::set-output name=pr_number::none"
       fi
-      - name: Checkout
-      uses: actions/checkout@v4
   - name: Build draft PDF
     uses: openjournals/openjournals-draft-action@master
     with:
